config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # overriding the registrations controller
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users
  end

  # for csv import export
  resources :artists do
    collection do
      get :export
      post :import
    end
  end

  resources :artists do
    resources :musics, only: %i[index create show update destroy]
  end

  # Default root route for unauthenticated users
  root to: 'home#index'

  # routes to manage individual music record by a particular 'artist' user
  resources :musics
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  validates :full_name, uniqueness: true

  validates :date_of_birth, :gender,
            :address, presence: true

  validates :no_of_albums_released,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0 }, allow_nil: true

  enum gender: { male: 'Male', female: 'Female', other: 'Other' }

  has_many :musics, dependent: :destroy, inverse_of: :artist

  belongs_to :user, optional: true

  accepts_nested_attributes_for :musics, allow_destroy: true, reject_if: :all_blank

  def self.build_artist_object_from_json(result)
    artists = []
    result.each do |artist|
      artists << Artist.new(artist)
    end

    artists
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update destroy]
  before_action :set_artist_for_export, only: %i[export]
  before_action :set_page_number, only: %i[index]

  require 'csv'
  require_relative './concerns/sql_queries'
  include DatabaseExecution
  include SQLQueries
  include ArtistMusicSqlHandler

  def index
    authorize Artist, :index?

    per_page = 5

    @artists = paginate_artists(per_page)
  end

  def new
    @artist = Artist.new

    authorize @artist

    @artist.musics.build
  end

  def show
    authorize @artist
  end

  def create
    ActiveRecord::Base.transaction do
      capitalize_artist_enum

      result = create_artist_record(artist_params)

      artist_id = result.first['id']

      create_artist_musics(artist_params[:musics_attributes], artist_id)

      redirect_to artists_path, notice: 'Artist and their musics were successfully created.'
    rescue StandardError => e
      flash.now[:alert] = "Failed to create artist and their musics: #{e.message}"
      render :new
    end
  end

  def edit
    authorize @artist
  end

  def update
    authorize @artist

    ActiveRecord::Base.transaction do
      update_artist_and_music
    end
    redirect_to artists_url, notice: 'Artist updated successfully.'
  rescue ActiveRecord::StatementInvalid
    flash[:alert] = 'Unable to update artist. Please try again.'
  end

  def destroy
    ActiveRecord::Base.transaction do
      delete_artist_and_associated_musics
    end
    redirect_to artists_url, notice: 'Artist deleted successfully.'
  rescue ActiveRecord::StatementInvalid
    flash[:alert] = 'Unable to delete artist and musics. Please try again.'
  end

  def export
    csv_data = CsvExportService.export_artists_and_musics

    authorize :artist, :export?

    send_data csv_data, filename: "artists_and_musics-#{Date.today}.csv", type: 'text/csv'
  end

  def import
    file = params[:file]

    if file.nil?
      redirect_to artists_url, alert: 'Please upload any file.'
      return
    end

    authorize :artist, :import?

    ActiveRecord::Base.transaction do
      CsvImportService.import_artists_and_musics(file)
    end
    redirect_to artists_path, notice: 'Artists and Musics were successfully imported.'
  rescue ActiveRecord::StatementInvalid
    redirect_to artists_path
    flash[:alert] = 'Unable to update artist. Please try again.'
  end

  private

  def artist_params
    params.require(:artist).permit(:date_of_birth, :gender, :full_name,
                                   :address, :first_released_year,
                                   musics_attributes: %i[id genre album_name title _destroy])
  end

  def capitalize_artist_enum
    params[:artist][:gender] = artist_params[:gender]&.capitalize
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def set_artist_for_export
    @artists = Artist.includes(:musics).all
  end

  def paginate_artists(per_page)
    artist_count_query = SQLQueries::COUNT_ARTISTS
    order_artist_query = SQLQueries::ORDER_ARTIST_RECORD

    pagination = PaginationService.new(artist_count_query, @page_number, per_page, order_artist_query)

    @total_pages = pagination.total_pages

    result = pagination.paginate

    Artist.build_artist_object_from_json(result)
  end

  def set_page_number
    @page_number = params[:page].to_i || 1
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist_and_music_fields.html.erb
    <% if @artist&.errors&.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Oops! There were some errors:</h4>
        <ul>
          <% @artist.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Artist Fields -->
    <div class="row mb-3">
      <div class="col-md-4">
        <%= form.label :full_name, class: 'form-label' %>
        <%= form.text_field :full_name, class: 'form-control form-control-sm', required: true, placeholder: 'Enter full name' %>
        <div class="invalid-feedback">Please provide a full name.</div>
      </div>

      <div class="col-md-4">
        <%= form.label :date_of_birth, class: 'form-label' %>
        <%= form.date_field :date_of_birth, class: 'form-control form-control-sm', required: true, placeholder: 'YYYY-MM-DD', max: Date.today.to_s %>
        <div class="invalid-feedback">Please provide a valid date of birth.</div>
      </div>

      <div class="col md-3">
        <%= form.label :gender, class: "form-label" %>
        <%= form.select :gender, humanized_gender_names, { prompt: 'Select Gender' }, class: "form-select form-select-sm", required: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-4">
        <%= form.label :first_released_year, class: 'form-label' %>
        <%= form.number_field :first_released_year, class: 'form-control form-control-sm', placeholder: 'Enter first released year' %>
        <div class="invalid-feedback">Please provide a valid year.</div>
      </div>

      <div class="col-md-4">
        <%= form.label :address, class: 'form-label' %>
        <%= form.text_area :address, class: 'form-control form-control-sm', required: true, placeholder: 'Enter address' %>
        <div class="invalid-feedback">Please provide an address.</div>
      </div>
    </div>
    <hr>

    <h4 class="mt-4 mb-3">Artist Music</h4>

    <!-- Template for new records -->
    <template data-nested-form-target="template">
      <%= form.fields_for :musics, Music.new, child_index: 'NEW_RECORD' do |music_fields| %>
        <%= render "music_form_fields", f: music_fields %>
      <% end %>
    </template>

    <!-- Existing records -->
    <%= form.fields_for :musics do |music_fields| %>
      <%= render "music_form_fields", f: music_fields %>
    <% end %>

    <div data-nested-form-target="target"></div>

    <button type="button" class="btn btn-secondary btn-sm" data-action="nested-form#add">Add Music</button>

app/views/artists/_music_form.html.erb
<div class="nested-form-wrapper row mb-3 align-items-center" data-new-record="<%= f.object.new_record? %>">
  <div class="col-md-4">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control form-control-sm', placeholder: 'Enter music title' %>
  </div>

  <div class="col-md-4">
    <%= f.label :album_name, class: 'form-label' %>
    <%= f.text_field :album_name, class: 'form-control form-control-sm', placeholder: 'Enter album name' %>
  </div>

  <div class="col md-3">
    <%= f.label :genre, class: "form-label" %>
   <%= f.select :genre, humanized_genre_names, { prompt: 'Select Genre' }, class: 'form-control form-control-sm', required: true %>  </div>

  <div class="col-md-2 d-flex justify-content-start align-items-center">
    <button type="button" class="btn btn-danger btn-sm remove-music-button" data-action="nested-form#remove">
      Remove
    </button>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/artists/_music_form_fields.html.erb
<div class="nested-form-wrapper row mb-3 align-items-center" data-new-record="<%= f.object&.new_record? %>">
  <div class="col-md-4">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control form-control-sm', placeholder: 'Enter music title' %>
  </div>

  <div class="col-md-4">
    <%= f.label :album_name, class: 'form-label' %>
    <%= f.text_field :album_name, class: 'form-control form-control-sm', placeholder: 'Enter album name' %>
  </div>
  
  <div class="col md-3">
    <%= f.label :genre, class: "form-label" %>
   <%= f.select :genre, humanized_genre_names, { prompt: 'Select Genre' }, class: 'form-select form-select-sm', required: true %>
  </div>

  <div class="col-md-2 d-flex justify-content-start align-items-center">
    <button type="button" class="btn btn-danger btn-sm remove-music-button" data-action="nested-form#remove">
      Remove
    </button>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/artists/destroy.html.erb
<h1>Artists#destroy</h1>
<p>Find me in app/views/artists/destroy.html.erb</p>

app/views/artists/edit.html.erb
<div class="container">
  <h4 class="mb-4">Edit Artist</h4>
  <%= form_with(model: @artist,
    data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper'}) do |form| %>

    <%= render "artists/artist_and_music_fields", form: form %>

    <div class="row mb-3">
      <div class="col-md-10 offset-md-4">
        <%= form.submit "Update", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/artists/index.html.erb
<div class="container">
  <h3 class="float-start">All Artists</h3>
  <% if current_user.artist_manager? %>
    <%= link_to "Add Artist", new_artist_path, class: "btn btn-primary float-end me-2" %>
  <% end %>

  <div class="row">
    <% if current_user.artist_manager? %>
      <div class="col-md-4"></div>
      <div class="col-md-2">
        <% if @artists.any? %>
          <%= link_to export_artists_path(format: :csv), class: "btn btn-success float-end" do %>
            <i class="bi bi-download"></i> Export
          <% end %>
        <% end %>
      </div>
      <div class="col-md-6">
        <%= form_tag import_artists_path, multipart: true do %>
          <div class="input-group">
            <%= file_field_tag :file, class: "form-control", id: "inputFile", accept: ".csv" %>
            <button type="submit" class="btn btn-primary">Import CSV</button>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if @artists.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date of Birth</th>
          <th>Gender</th>
          <th>Address</th>
          <th>First Released Year</th>
          <th>No. of Albums Released</th>
          <% if current_user.artist_manager? %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @artists.each do |artist| %>
          <tr>
            <td><%= link_to artist.full_name, artist_path(artist) %></td>
            <td><%= artist.date_of_birth&.strftime('%Y-%m-%d') %></td>
            <td><%= artist.gender %></td>
            <td><%= artist.address %></td>
            <td><%= artist.first_released_year %></td>
            <td><%= artist.no_of_albums_released %></td>
            <% if current_user.artist_manager? %>
              <td>
                <%= link_to "Edit", edit_artist_path(artist), class: "btn btn-secondary btn-sm" %>
                <%= button_to "Delete", artist_path(artist), method: :delete, 
                              data: { turbo_confirm: "Are you sure you want to delete #{artist.full_name} and their music?" },
                              class: "btn btn-danger btn-sm" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= render 'shared/paginate', path: artists_path, page_number: @page_number, total_pages: @total_pages if @total_pages > 1 %>
  <% else %>
    <p>No artists found.</p>
  <% end %>
</div>

app/views/artists/new.html.erb
<div class="container">
  <h4 class="mb-4">Artist Artist</h4>
  <%= form_with(model: @artist,
    data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper'}) do |form| %>
    <%= render "artist_and_music_fields", form: form %>
    <div class="row mb-3">
      <div class="col-md-10">
        <%= form.submit "Create", class: "btn btn-primary btn-lg offset-6" %>
      </div>
    </div>

  <% end %>
</div>

app/views/artists/show.html.erb
<div class="container mt-4">
  <h3>Artist Details</h3>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Full Name</th>
        <td><%= @artist.full_name %></td>
      </tr>
      <tr>
        <th>Date of Birth</th>
        <td><%= @artist.date_of_birth %></td>
      </tr>
      <tr>
        <th>Gender</th>
        <td><%= @artist.gender %></td>
      </tr>
      <tr>
        <th>Address</th>
        <td><%= @artist.address %></td>
      </tr>
      <tr>
        <th>First Released Year</th>
        <td><%= @artist.first_released_year %></td>
      </tr>
    </tbody>
  </table>

  <h4 class="mt-4">Associated Musics</h4>

  <% if @artist.musics.any? %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Album Name</th>
          <th>Genre</th>
        </tr>
      </thead>
      <tbody>
        <% @artist.musics.each do |music| %>
          <tr>
            <td><%= music.title %></td>
            <td><%= music.album_name %></td>
            <td><%= music.genre %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-muted">No music records associated with this artist.</p>
  <% end %>

  <div class="mt-3">
    <%= link_to 'Back to Artists', artists_path, class: 'btn btn-secondary btn-sm' %>
  </div>
</div>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>