config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # overriding the registrations controller
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users
  end

  # for csv import export
  resources :artists do
    collection do
      get :export
      post :import
    end
  end

  resources :artists do
    resources :musics, only: %i[index create show update destroy]
  end

  # Default root route for unauthenticated users
  root to: 'home#index'

  # routes to manage individual music record by a particular 'artist' user
  resources :musics
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ArtistManagement", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <% if current_user.super_admin? %>
          <li class="nav-item">
            <%= link_to "Users", root_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user.super_admin? || current_user.artist_manager? %>
          <li class="nav-item">
            <%= link_to "Artists", artists_path, class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link", data: { turbo: false } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_paginate.html.erb
<div class="pagination-container text-center">
  <ul class="pagination">
    <% if @page_number > 1 %>
      <li class="page-item"><%= link_to 'Previous', "#{path}?page=#{@page_number - 1}", class: "page-link" %></li>
    <% end %>

    <% (1..@total_pages).each do |page| %>
      <li class="page-item"><%= link_to page, "#{path}?page=#{page}", class: "page-link" %></li>
    <% end %>

    <% if @page_number < @total_pages %>
      <li class="page-item"><%= link_to 'Next', "#{path}?page=#{@page_number + 1}", class: "page-link" %></li>
    <% end %>
  </ul>
</div>