config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # overriding the registrations controller
  devise_for :users, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users
  end

  # for csv import export
  resources :artists do
    collection do
      get :export
      post :import
    end
  end

  resources :artists do
    resources :musics, only: %i[index create show update destroy]
  end

  # Default root route for unauthenticated users
  root to: 'home#index'

  # routes to manage individual music record by a particular 'artist' user
  resources :musics
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :artist, inverse_of: :musics

  enum genre: { pop: 0, country: 1, classic: 2, rock: 3, jazz: 4 }

  validates :title, :album_name, :genre, presence: true
end

app/controllers/musics_controller.rb
# frozen_string_literal: true

class MusicsController < ApplicationController
  before_action :set_music, only: %i[show edit destroy update]

  include ArtistMusicSqlHandler
  require_relative './concerns/sql_queries'
  include DatabaseExecution

  def index
    authorize Music, :index?

    @musics = current_user&.artist&.musics
  end

  def new
    @music = Music.new
    authorize @music
  end

  def create
    authorize :music, :create?

    artist_id = current_user&.artist&.id

    ActiveRecord::Base.transaction do
      @music = create_music(artist_id, music_params)

      redirect_to musics_path, notice: 'Music was successfully created.'
    end
  rescue StandardError => e
    Rails.logger.error("Music creation failed: #{e.message}")
    render :new, alert: 'Music creation failed. Please try again.'
  end

  def show
    authorize @music
  end

  def edit
    authorize @music
  end

  def update
    authorize @music

    ActiveRecord::Base.transaction do
      success = update_music_single(@music.id, music_params)

      raise ActiveRecord::Rollback, 'Music update failed' unless success

      redirect_to musics_path, notice: 'Music was successfully updated.'
    end
  rescue StandardError => e
    Rails.logger.error("Music update failed: #{e.message}")
    render :edit, status: :unprocessable_entity, alert: 'Music update failed. Please try again.'
  end

  def destroy
    authorize @music

    ActiveRecord::Base.transaction do
      success = delete_music(@music.id)

      raise ActiveRecord::Rollback, 'Music deletion failed' unless success

      redirect_to musics_path, notice: 'Music was successfully deleted.'
    end
  rescue StandardError => e
    Rails.logger.error("Music deletion failed: #{e.message}")
    redirect_to musics_path, alert: 'Failed to delete Music. Please try again.'
  end

  private

  def set_music
    @music = find_music_by_id(params[:id])
    raise ActiveRecord::RecordNotFound, 'Music not found' unless @music
  end

  def music_params
    params.require(:music).permit(:title, :album_name, :genre)
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_music_fields.html.erb
<div class="music-form row mb-3 justify-content-center">
  <div class="col-md-5 offset-md-1">
    <%= f.label :title, "Title", class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control form-control-sm', placeholder: 'Enter music title', required: true %>
  </div>
</div>

<div class="music-form row mb-3 justify-content-center">
  <div class="col-md-5 offset-md-1">
    <%= f.label :album_name, "Album Name", class: 'form-label' %>
    <%= f.text_field :album_name, class: 'form-control form-control-sm', placeholder: 'Enter album name', required: true %>
  </div>
</div>

<div class="music-form row mb-3 justify-content-center">
  <div class="col-md-5 offset-md-1">
    <%= f.label :genre, "Genre", class: 'form-label' %>
    <%= f.select :genre, options_for_select(humanized_genre_names, @music.genre), { prompt: "Select Genre" }, class: 'form-select form-select-sm' %>
  </div>
</div>

app/views/musics/edit.html.erb
<div class="container">
  <h4 class="mb-4">Edit Music</h4>
  <%= form_with(model: @music, local: true) do |form| %>
  
    <%= render 'music_fields', f: form %>

    <div class="music-form row mb-3 justify-content-center">
      <div class="col-md-5 offset-md-5">
        <%= form.submit "Update Music", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/musics/index.html.erb
<div class="mx-5">
  <div class="d-flex justify-content-between">
    <h3>My Musics</h3>
    <%= link_to "Add Music", new_music_path, class: "btn btn-primary" %>
  </div>

  <div class="row">
    <div class="col-12">
      <% if @musics.present? %>
        <table class="table table-striped w-100">
          <thead>
            <tr>
              <th>Title</th>
              <th>Album Name</th>
              <th>Genre</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @musics.each do |music| %>
              <tr>
                <td><%= music.title %></td>
                <td><%= music.album_name %></td>
                <td><%= music.genre %></td>
                <td>
                  <%= link_to 'Edit', edit_music_path(music), class: 'btn btn-primary btn-sm' %>
                  <%= button_to "Delete", music_path(music), method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this music?" } }, class: "btn btn-danger btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="alert alert-info">
          <p>You have no music yet. But you can add one by clicking Add Music button.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/musics/new.html.erb
<div id="music-forms-container" class="mx-5">
  <%= form_with(model: @music, local: true) do |f| %>

    <%= render 'music_fields', f: f %>

    <div class="music-form row mb-3 justify-content-center">
      <div class="col-md-5 offset-md-5">
        <%= f.submit "Save Music", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>